name: "blast_html"
description: |
  Basic Local Alignment Search Tool (BLAST) compares a query sequence to a database of sequences 
  to identify regions of similarity.
keywords:
  - blast search
  - nucleotide sequence
  - contiguous consensus
  - BLAST archive format
components:
  - ncbi/blast
  - python/pandas
input:
  - sample:
      type: val
      description: |
        sample name
  - tsv_doc:
      type: file
      description: Path to input Blast tabular file with comment lines
      pattern: "*.tsv"
  - html_doc:
      type: file
      description: Path to input Blastn HTML page
      pattern: "*.html"
output:
  - sample:
      type: val
      description: |
        sample name
  - html:
      type: file
      description: Blastn query results with the percent of identity in HTML format 
      pattern: "*.html"
  - versions:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"