name: "sangerseq_batch"
description: |
  Assembling Sanger sequencing data into contiguous consensus reads
keywords:
  - rscript
  - Sanger sequencing
  - Trace or ab1 file
  - 16S rRNA gene
  - Electropherogram or chromatogram
  - Alignment and contig assembly
components:
  - r/sangerseq
  - r/sangerAnalyseR
  - r/optparse
input:
  - sample:
      type: val
      description: |
        sample name
  - trace_files:
      type: list
      description: Path to input forward and reverse trace files
      pattern: "*.ab1"
output:
  - sample:
      type: val
      description: |
        sample name
  - contig:
      type: file
      description: Assembled contiguous consensus reads
      pattern: "*.txt"
  - fasta:
      type: file
      description: Text-based files that stores sequencing reads
      pattern: "*.fa"
  - chromatogram:
      type: file
      description: Two-dimensional plot with the ordinate axis giving signal strength
      pattern: "*.pdf"
  - metrics:
      type: file
      description: Quality Control metrics
      pattern: "*.csv"
  - versions:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"